### ISSUE TITLE
Refactor unwind-x64.cpp to be platform independent

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#103]
Currently this file recalls the HHVM platform independent method but it's explicitly referenced on other files without an arch dependent switch.

Check how `unique-stubs.cpp` calls function from `unique-stubs-ppc64.cpp` or `unique-stubs.x64.cpp`.   It should use a similar method to the unwind-x64.cpp so our unwind can be ported to unwind-ppc64.cpp.
- [x] Refactor the code on master branch as explained above
- [x] Fill up a Pull Request to HHVM with that code without any ppc64 unwind information (just to get the structure right).
- [x] Implement the ppc64 unwind in its separated file `unwind-ppc64.cpp` by making use of the specific code currently insie of `unwind-x64.cpp` like [this](https://github.com/PPC64/hhvm/commit/0b3e9df00a95171e6a04194d4c2026752e06d1e5) and [this](https://github.com/PPC64/hhvm/commit/e005599ab9be8809db27e6735bab9b885400c913).

**Comment by racardoso** [comment]
First subtask finished.  04dbb6ced9afbc72496fa189f483787e97fefbd9

**Comment by racardoso** [comment]
https://reviews.facebook.net/D52917

**Comment by gut** [comment]
This refactor needs to be readapted. Look at this change on facebook's master:
https://github.com/facebook/hhvm/commit/a24c91bb554f3d119a3c99cad548339cf049663f#diff-89a4cfe39039aac12ea5ef9ace7e31db

**Comment by racardoso** [comment]
yes @gut. I don't expect that max wang would do that fast. That's great news because i was waiting for those changes to refactor the code.
