### ISSUE TITLE
Investigate why "hphp/test/quick/continuation-funcname.php" test crashes sometimes

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#106]
After running `hphp/test/run` 10 times, I noticed that the test "hphp/test/quick/continuation-funcname.php" crashed sometimes. That's the reason why test results is +-1.

**Comment by gromero** [comment]
Interesting. But I also caught some cases where +/- 2 happens, so probably there are other tests like this one...

**Comment by gut** [comment]
interesting. I'll run the tests more times then and re-analyse. Thanks

**Comment by gut** [comment]
well, the "hphp/test/quick/continuation-funcname.php" test doesn't crash with gdb :(. Checking other things...

**Comment by gut** [comment]
The problem was this:

```
(gdb) show disable-randomization
Disabling randomization of debuggee's virtual address space is on.
```

When the program runs directly in the shell, the kernel uses virtual address randomization:
http://stackoverflow.com/a/17775333/5013070

to solve it, simply: `set disable-randomization off`. Now I have the same behavior...

**Comment by gromero** [comment]
Nice find!
