### ISSUE TITLE
Fix 'hphp/test/quick/allbranches.php' mistakes

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#111]
Currently, these entries are wrongly output on that test (snippet):

```
0 < -1
1 < -1
-1 !== -1
-1 != -1
-1 < -1
-1 > -1
-1 !== -1
-1 != -1
-1 < -1
-1 > -1
0 > 1
-1 > 1
1 !== 1
1 != 1
1 < 1
1 > 1
1 !== 1
1 != 1
1 < 1
1 > 1
```

and it doesn't recognize that:

```
0 >= -1
0 === 0
0 == 0
0 <= 0
0 >= 0
0 !== 1
0 != 1
0 <= 1
0 < 1
1 >= -1
1 !== 0
1 != 0
1 >= 0
1 > 0
1 === 1
1 == 1
1 <= 1
1 >= 1
-1 === -1
-1 == -1
-1 <= -1
-1 >= -1
-1 !== 0
-1 != 0
-1 <= 0
-1 < 0
-1 !== 1
-1 != 1
-1 <= 1
-1 < 1
```

**Comment by gut** [comment]
a related issue that is also interesting:

```
<?php
foreach (array(0,1,2) as $l) foreach (array('a','b','c') as $r) {
  echo "$l $r\n";
}
?>
```

That outputs only:

```
0 a
0 b
0 c
1 a
2 a
```

it misses the `1 b`, `1 c`, `2 b`, `2 c`.

**Comment by gut** [comment]
I think I found the culprit:
https://github.com/PPC64/hhvm/blob/next/hphp/runtime/vm/jit/mc-generator.cpp#L1057

damn hardcoded X64 `DecodedInstruction`! It should call `smashableJccTarget` but it calls `smashableJmpTarget`, and for this reason it's addicted to one path.

**Comment by racardoso** [comment]
We need to implement those methods Decoder methods on our ppc decoder.

**Comment by gut** [comment]
task #113 will continue to implement all methods of this new `decoded-instr-ppc64` file
