### ISSUE TITLE
HHVM fails 400 tests on Release Mode

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#116]
HHVM quick test fails 400 tests against 30 on Debug mode:

400 tests failed
(╯°□°）╯︵ ┻━┻

See the diffs:
cat quick/IncDecProp.php.diff
cat quick/IncDecProp_nopt.php.diff
cat quick/ReflectionClass.php.diff
cat quick/SetM-str-promotion.php.diff
cat quick/SetM.php.diff
cat quick/SetOpProp.php.diff
cat quick/UnsetProp.php.diff
cat quick/__isset.php.diff
cat quick/abs_codegen.php.diff
cat quick/actrec.php.diff
cat quick/alias_torture.php.diff
cat quick/all_type_comparison_test.php.diff
cat quick/allbranches.php.diff
cat quick/apc-sleep.php.diff
cat quick/array-set-ref-catch.php.diff
cat quick/array_access.php.diff
cat quick/array_helper_reenter.php.diff
cat quick/array_misc.php.diff
cat quick/array_packed.php.diff
cat quick/array_plus_eq_dtor.php.diff
cat quick/asm_assert_optobj.hhas.diff
cat quick/asm_cont.hhas.diff
cat quick/asm_dvinit_fault.hhas.diff
cat quick/asm_fatal_await.hhas.diff
cat quick/asm_fault.hhas.diff
cat quick/asm_fault_endings.hhas.diff
cat quick/asm_hoistable_3.hhas.diff
cat quick/asm_prop_init.hhas.diff
cat quick/asm_ret_type.hhas.diff
cat quick/asm_sswitch_slow.hhas.diff
cat quick/asm_types.hhas.diff
cat quick/autoload.php.diff
cat quick/autoload2.php.diff
cat quick/autoload6.php.diff
cat quick/autoload7.php.diff
cat quick/autoload_case.php.diff
cat quick/backtrace-after-unset.php.diff
cat quick/bad_setm.php.diff
cat quick/bad_setm_nopt.php.diff
cat quick/builtin_call.php.diff
cat quick/builtin_extension_DOMAttr.php.diff
cat quick/builtin_extension_DOMCDATASection.php.diff
cat quick/builtin_extension_DOMCharacterData.php.diff
cat quick/builtin_extension_DOMComment.php.diff
cat quick/builtin_extension_DOMDocument.php.diff
cat quick/builtin_extension_DOMDocumentFragment.php.diff
cat quick/builtin_extension_DOMDocumentType.php.diff
cat quick/builtin_extension_DOMElement.php.diff
cat quick/builtin_extension_DOMEntity.php.diff
cat quick/builtin_extension_DOMEntityReference.php.diff
cat quick/builtin_extension_DOMImplementation.php.diff
cat quick/builtin_extension_DOMNamedNodeMap.php.diff
cat quick/builtin_extension_DOMNode.php.diff
cat quick/builtin_extension_DOMNodeIterator.php.diff
cat quick/builtin_extension_DOMNodeList.php.diff
cat quick/builtin_extension_DOMNotation.php.diff
cat quick/builtin_extension_DOMProcessingInstruction.php.diff
cat quick/builtin_extension_DOMText.php.diff
cat quick/builtin_extension_DOMXPath.php.diff
cat quick/builtin_extension_DateInterval.php.diff
cat quick/builtin_extension_DateTime.php.diff
cat quick/builtin_extension_DateTimeZone.php.diff
cat quick/builtin_extension_LibXMLError.php.diff
cat quick/builtin_extension_Memcache.php.diff
cat quick/builtin_extension_Memcached.php.diff
cat quick/builtin_extension_SQLite3.php.diff
cat quick/builtin_extension_SQLite3Result.php.diff
cat quick/builtin_extension_SQLite3Stmt.php.diff
cat quick/builtin_extension_SimpleXMLElement.php.diff
cat quick/builtin_extension_SimpleXMLElementIterator.php.diff
cat quick/builtin_extension_SimpleXMLIterator.php.diff
cat quick/builtin_extension_SoapClient.php.diff
cat quick/builtin_extension_SoapHeader.php.diff
cat quick/builtin_extension_SoapParam.php.diff
cat quick/builtin_extension_SoapServer.php.diff
cat quick/builtin_extension_XMLReader.php.diff
cat quick/builtin_extension_XMLWriter.php.diff
cat quick/builtin_recurse.php.diff
cat quick/call_callable.php.diff
cat quick/callable-namespace.php.diff
cat quick/callable.php.diff
cat quick/catch-order.php.diff
cat quick/cgetm_ge.php.diff
cat quick/cgetm_hee.php.diff
cat quick/chdir.php.diff
cat quick/class_constants.php.diff
cat quick/class_exists_throw.php.diff
cat quick/class_inaccessible_private.php.diff
cat quick/class_interface_trait_exists.php.diff
cat quick/class_invalid_context.php.diff
cat quick/clone.php.diff
cat quick/closure.php.diff
cat quick/closure_func_get_arg.php.diff
cat quick/closure_gen.php.diff
cat quick/closure_gen_scope.php.diff
cat quick/closure_in_generator.php.diff
cat quick/closure_in_generator2.php.diff
cat quick/closure_lifetime.php.diff
cat quick/closure_recursive_bad.php.diff
cat quick/closure_static.php.diff
cat quick/cnsu.php.diff
cat quick/cnvDbl.php.diff
cat quick/cnvInt.php.diff
cat quick/cnvStr.php.diff
cat quick/collection-exceptions.php.diff
cat quick/collection-initializer.php.diff
cat quick/compact.php.diff
cat quick/concat_equal.php.diff
cat quick/constants-SID.php.diff
cat quick/constants.php.diff
cat quick/constructor_throw.php.diff
cat quick/continuation_serialize.php.diff
cat quick/countable.php.diff
cat quick/create_function.php.diff
cat quick/cuf-byref.php.diff
cat quick/cuf-call10.php.diff
cat quick/cuf-call11.php.diff
cat quick/cuf03.php.diff
cat quick/cuf04.php.diff
cat quick/cuf05.php.diff
cat quick/cuf__callStatic1.php.diff
cat quick/cuf__callStatic4.php.diff
cat quick/cuf__callStatic5.php.diff
cat quick/cyclic_setop_props.php.diff
cat quick/datetime.php.diff
cat quick/debug_backtrace.php.diff
cat quick/debug_backtrace_continuation.php.diff
cat quick/debug_backtrace_multiline.php.diff
cat quick/debug_backtrace_trait.php.diff
cat quick/debugger/async_stack.php.diff
cat quick/debugger/async_stack_traversal.php.diff
cat quick/debugger/break1.php.diff
cat quick/debugger/eval2.php.diff
cat quick/debugger/exception1.php.diff
cat quick/debugger/flow.php.diff
cat quick/debugger/flow2.php.diff
cat quick/debugger/flow_break_interference.php.diff
cat quick/debugger/flow_excep.php.diff
cat quick/debugger/flow_gen.php.diff
cat quick/debugger/flow_gen_async.php.diff
cat quick/debugger/flow_gen_async_excep.php.diff
cat quick/debugger/flow_gen_excep.php.diff
cat quick/debugger/flow_iterator_continue.php.diff
cat quick/debugger/flow_multistep.php.diff
cat quick/debugger/flow_small.php.diff
cat quick/debugger/stack1.php.diff
cat quick/decrefstack1.php.diff
cat quick/define.php.diff
cat quick/destruct.php.diff
cat quick/destruct_segfault.php.diff
cat quick/destructed_this.php.diff
cat quick/div-zero.php.diff
cat quick/dtor-on-arr.php.diff
cat quick/dynamic_eval.php.diff
cat quick/enormous-string.php.diff
cat quick/eq_int_str.php.diff
cat quick/exception_bug_1351681.php.diff
cat quick/exception_bug_2080454.php.diff
cat quick/exception_bug_more.php.diff
cat quick/exception_destructor_1.php.diff
cat quick/exception_destructor_3.php.diff
cat quick/exception_destructor_4.php.diff
cat quick/exception_handler.php.diff
cat quick/exception_many_locals.php.diff
cat quick/exception_set_previous_chain.php.diff
cat quick/exceptions.php.diff
cat quick/exceptions4.php.diff
cat quick/exceptions7.php.diff
cat quick/exceptions8.php.diff
cat quick/exceptions_clone.php.diff
cat quick/ext_pdo_exception.php.diff
cat quick/ext_pdo_fetchobject_no_class_name.php.diff
cat quick/ext_pdo_queryString.php.diff
cat quick/extension_null_check.php.diff
cat quick/extract.php.diff
cat quick/fail_86pinit.php.diff
cat quick/fail_86sinit.php.diff
cat quick/fail_self.php.diff
cat quick/fb_dbt.php.diff
cat quick/fb_intercept.php.diff
cat quick/fc_enum_3.php.diff
cat quick/fc_enum_4.php.diff
cat quick/fc_enum_7.php.diff
cat quick/fc_enum_8.php.diff
cat quick/fc_enum_9.php.diff
cat quick/fib_gen.php.diff
cat quick/float-overflow.php.diff
cat quick/floatcmp.php.diff
cat quick/foreach-list.php.diff
cat quick/fpush_fatal.php.diff
cat quick/func_get_args.php.diff
cat quick/func_get_args_namespace.php.diff
cat quick/function_varargs.php.diff
cat quick/gcv.php.diff
cat quick/generator_cond_func.php.diff
cat quick/generator_method.php.diff
cat quick/generator_varargs.php.diff
cat quick/generator_vars.php.diff
cat quick/get_class.php.diff
cat quick/get_class_constants.php.diff
cat quick/get_class_methods1.php.diff
cat quick/get_class_methods2.php.diff
cat quick/get_class_methods3.php.diff
cat quick/get_class_methods4.php.diff
cat quick/get_defined_vars.php.diff
cat quick/getter-magic.php.diff
cat quick/global-obj-dtor.php.diff
cat quick/global_addelem.php.diff
cat quick/hh_async_closure_return_type_1.php.diff
cat quick/hh_async_closure_return_type_2.php.diff
cat quick/hh_async_closure_return_type_3.php.diff
cat quick/hh_async_return_type_1.php.diff
cat quick/hh_async_return_type_2.php.diff
cat quick/hh_async_return_type_3.php.diff
cat quick/hh_closure_return_type_1.php.diff
cat quick/hh_closure_return_type_2.php.diff
cat quick/hh_closure_return_type_3.php.diff
cat quick/hh_softtype1.php.diff
cat quick/hh_softtype4.php.diff
cat quick/hh_typehint1.php.diff
cat quick/hh_typehint5.php.diff
cat quick/hhir_cgetm_exceptions.php.diff
cat quick/hhir_eq_stack.php.diff
cat quick/hoistable_c.php.diff
cat quick/hoistable_e.php.diff
cat quick/hopt-exit-ref1.php.diff
cat quick/hopt-ret6.php.diff
cat quick/hopt-ret7.php.diff
cat quick/hopt-ret8.php.diff
cat quick/hopt-ret9.php.diff
cat quick/hopt-string-simp.php.diff
cat quick/hopt-translator_unwind.hhas.diff
cat quick/hopt_sprop_accessibility.php.diff
cat quick/iconv_stream_filter.php.diff
cat quick/incdec-magic.php.diff
cat quick/incdec-magic2.php.diff
cat quick/incdec-magic3.php.diff
cat quick/incdec-magic4.php.diff
cat quick/incdec-magic5.php.diff
cat quick/include_backtrace.php.diff
cat quick/incorrect-arguments.php.diff
cat quick/inittrace.php.diff
cat quick/intercept.php.diff
cat quick/intercept2.php.diff
cat quick/invoke.php.diff
cat quick/is_callable.php.diff
cat quick/lambda2.php.diff
cat quick/lambda7.php.diff
cat quick/libxml_suppress_errors.php.diff
cat quick/list-assignment.php.diff
cat quick/magic-get-dtors.php.diff
cat quick/magic-get-set.php.diff
cat quick/method-non-object.php.diff
cat quick/method-non-object2.php.diff
cat quick/method-undefined.php.diff
cat quick/missing_arg_exception.php.diff
cat quick/mod.php.diff
cat quick/mod_zero.php.diff
cat quick/multidim_props.php.diff
cat quick/nested__destruct.php.diff
cat quick/nested_parens.php.diff
cat quick/nested_vm_exceptions.php.diff
cat quick/nested_vm_exceptions2.php.diff
cat quick/no_arg_class_alias.php.diff
cat quick/no_more_id_crazy.php.diff
cat quick/no_return_function.php.diff
cat quick/non-special-this.php.diff
cat quick/nonstrict_hashbang_start.php.diff
cat quick/nonstrict_hashbang_whitespace_start.php.diff
cat quick/not-enough-args.php.diff
cat quick/ns_existing_names.php.diff
cat quick/ns_gen_func_get_args.php.diff
cat quick/ns_initial_backslash.php.diff
cat quick/ns_invalid_class.php.diff
cat quick/ns_invalid_const.php.diff
cat quick/ns_invalid_func.php.diff
cat quick/ns_reflection.php.diff
cat quick/ns_use_const.php.diff
cat quick/ns_use_func.php.diff
cat quick/null_this.php.diff
cat quick/obj-string-throw.php.diff
cat quick/objmethod.php.diff
cat quick/openssl_binarysafety.php.diff
cat quick/ops.php.diff
cat quick/param-type.php.diff
cat quick/pcre_limit.php.diff
cat quick/pinit.php.diff
cat quick/poly-torture.php.diff
cat quick/priv1.php.diff
cat quick/priv5.php.diff
cat quick/priv6.php.diff
cat quick/profile/Setprofile.php.diff
cat quick/profile/Setprofile_async.php.diff
cat quick/profile/Setprofile_generic.php.diff
cat quick/profile/setprofile-this.php.diff
cat quick/profile/setprofile_throw.php.diff
cat quick/prop-access-error1.php.diff
cat quick/prop-access-error2.php.diff
cat quick/prop_ctx.php.diff
cat quick/prop_order_parens.php.diff
cat quick/properties-dynamic.php.diff
cat quick/properties3.php.diff
cat quick/properties4.php.diff
cat quick/protected-magic-getter.php.diff
cat quick/protected-magic-getter2.php.diff
cat quick/pseudomain1.php.diff
cat quick/raise_array_index_notice.php.diff
cat quick/recursive-getter.php.diff
cat quick/recursive-isset.php.diff
cat quick/recursive-setter.php.diff
cat quick/recursive-unset.php.diff
cat quick/refcount-static.php.diff
cat quick/reflect-default.php.diff
cat quick/reflection2.php.diff
cat quick/reflection_default_param.php.diff
cat quick/reflection_get_closure.php.diff
cat quick/reflection_noconstuctor.php.diff
cat quick/regpressure_bug.php.diff
cat quick/rename_dyn_function.php.diff
cat quick/resource.php.diff
cat quick/resurrect.php.diff
cat quick/retc-destruct.php.diff
cat quick/retval_backtrace.php.diff
cat quick/setHelperPreError.php.diff
cat quick/set_toarray_warn.php.diff
cat quick/setg-dtor.php.diff
cat quick/seth-dtor.php.diff
cat quick/seth-dtor3.php.diff
cat quick/setm-method.php.diff
cat quick/setop-magic.php.diff
cat quick/setop-magic2.php.diff
cat quick/setop-magic3.php.diff
cat quick/setop-magic4.php.diff
cat quick/setop-magic5.php.diff
cat quick/setop-refleak.php.diff
cat quick/sets-dtor.php.diff
cat quick/setter-magic.php.diff
cat quick/setter-magic2.php.diff
cat quick/shiftDtorOrder.php.diff
cat quick/silencer.php.diff
cat quick/sqrt.php.diff
cat quick/stack_overflow.php.diff
cat quick/static_closure_gen.php.diff
cat quick/static_clsmethod.php.diff
cat quick/static_fatal.php.diff
cat quick/static_prop_eval_order.php.diff
cat quick/static_sprop2.php.diff
cat quick/strict_hashbang_start.php.diff
cat quick/string_int_arith.php.diff
cat quick/string_replace_overflow.php.diff
cat quick/strlen_non_integer.php.diff
cat quick/surprise_throw.php.diff
cat quick/switch_special_cases.php.diff
cat quick/this-type.php.diff
cat quick/throw.php.diff
cat quick/tobadtype.php.diff
cat quick/too-few-args.php.diff
cat quick/tostring_throw.php.diff
cat quick/tostring_throw_setopl.php.diff
cat quick/trait_property_init.php.diff
cat quick/trait_two_use_closure.php.diff
cat quick/traits.php.diff
cat quick/translator_unwind.hhas.diff
cat quick/trim_dtor.php.diff
cat quick/typechecks-dv.php.diff
cat quick/typechecks-obj.php.diff
cat quick/typehint_arraykey.php.diff
cat quick/typehint_callable.php.diff
cat quick/typehint_lsb_parent.php.diff
cat quick/typehint_lsb_self.php.diff
cat quick/typehint_number.php.diff
cat quick/undefined-bases.php.diff
cat quick/undefined-class.php.diff
cat quick/undefined-index.php.diff
cat quick/undefined-variable.php.diff
cat quick/undefined_is_type.php.diff
cat quick/unserialize_assert.php.diff
cat quick/unset-decl-prop.php.diff
cat quick/unset_badbase.php.diff
cat quick/unused_clscns.php.diff
cat quick/unwind_backtrace.php.diff
cat quick/user_func.php.diff
cat quick/varenv_extra_args.php.diff
cat quick/vector-clscns.php.diff
cat quick/vector-stack-base.php.diff
cat quick/vector-unwind-decref.php.diff
cat quick/vector-variant-key.php.diff
cat quick/verify-param-type.php.diff
cat quick/weird_properties.php.diff
cat quick/xenon/xenon.php.diff
cat quick/xenon/xenon_crash.php.diff
cat quick/xenon/xenon_frame_metadata.php.diff
cat quick/xenon/xenon_init.php.diff
cat quick/xhp_comment.php.diff
cat quick/xml_entity_loader.php.diff
cat quick/yield_pair.php.diff
cat quick/zend_bug54265.php.diff
cat quick/zend_closure_005.php.diff
cat quick/zend_closure_020.php.diff
cat quick/zend_indirect_method_call_005.php.diff

**Comment by gut** [comment]
problem seems to be around changing the code from `-O0` on debug to `-O3` on release

**Comment by gut** [comment]
Ok, the problem (at least on the `hphp/test/quick/sqrt.php`, that should pass) relies on a common code that is called for handling exceptions (bunch of tests. Mostly those fix by unwind).

On `fixupMap::fixup` the frame pointer is copied through `DECLARE_FRAME_POINTER(framePtr)` and used as a parameter to the call of `fixupWork`. By using `-O3` otimization, the `FixupMap::fixup` call is detected to a be a tailcall and it optimizes performing a tailcall elimination. 

The issue by doing that is that this frame pointer is now invalid, as it doesn't exist anymore as the frame was removed prior to the `fixupWork` call. After the call the function overwrites the memory on its prologue (perfectly fine accordinging to ABI, as nobody owns anything below the stack pointer so it's free to overwrite that).

**Comment by racardoso** [comment]
can we solve this something like `__attribute__((optimize("-fno-omit-frame-pointer")))` to avoid this optimization on `fixupMap::fixup`?

**Comment by gut** [comment]
it's not a problem of the frame pointer being used or not, but tail call optimization.

**Comment by racardoso** [comment]
@gut  I saw you close the issue due 09f4b14 but there 1004 tests of quick suite passing against 1011 tests on Release mode. I think you should reopen the issue until we have the same tests passing in both modes Debug and Release.

**Comment by gut** [comment]
I'd open another task for that. I guess we are not afraid anymore that we
have a huge issue on release, right?

I'll do it shortly then.
