### ISSUE TITLE
Analize strange behavior of lowering loadups

### ISSUE THREAD

**Issue by igorsnunes** [PPC64/hhvm#118]
To analize this issue, it is necessary to checkout a commit before 17a9088831d9a2ccbb571ec163549c772b3e9ff5 , and run the following test:

``` php
<?php
$x = 42;
$a = array(0,$x,0,0,0,0,0,0,0,0,0,12); var_dump($a);
```

And then analize (breakpoint the code) the lower function for "loadups" and also the vasm loadups.

When lowering loadups, the function patchVptr is called in order to fit the operands in register. A "shift" operation is emitted to adjust the "scale" and nothing else is made, once the parameter "disp",  in the source operand,  is zero.

After the lowering operation, the vasm is emmited in "emit(const loadups& i)" . But in this context, the "disp" parameter in source operand is not zero anymore (disp is now -208) , causing the necessity to adjust the operands for "lxvw4x" . But nothing can be done, once the lower was already made.

It was expected that the value "disp" parameter did not change between the lowering and the vasm emmition. Probably, the value -208 should be present in the lowering parameters.

A first analysis showed that the "disp" parameter is changed in vasm-copy.cpp:294 . But I could not get to an answer.

See commit 17a9088831d9a2ccbb571ec163549c772b3e9ff5 to see the workaround developed.

**Comment by gromero** [comment]
Yep,  for some reason... I don't know either :/

**Comment by racardoso** [comment]
I guess this is already solved. Can we close this?

**Comment by gut** [comment]
yes. You tested it on #138, right? If so, there is no strange behavior anymore.

**Comment by racardoso** [comment]
I was testing it now and i don't see this behavior anymore.

**Comment by racardoso** [comment]
I will close this.
