### ISSUE TITLE
Solve remaining issues from release mode when comparing to debug mode

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#119]
Currently (d7a3d48) there are 7 tests less passing on release mode.

Tests that are passing only on release mode:

```
hphp/test/quick/SetOpM.php
hphp/test/quick/function_varargs.php
hphp/test/quick/sp.php
hphp/test/quick/generator_varargs.php
```

Tests that are passing only on debug mode:

```
hphp/test/quick/constants-SID.php
hphp/test/quick/hh_async_closure_return_type_1.php
hphp/test/quick/lambda7.php
hphp/test/quick/closure_static.php
hphp/test/quick/hh_async_closure_return_type_2.php
hphp/test/quick/hh_async_closure_return_type_3.php
hphp/test/quick/hh_closure_return_type_1.php
hphp/test/quick/rename_dyn_function.php
hphp/test/quick/hh_closure_return_type_2.php
hphp/test/quick/hh_closure_return_type_3.php
hphp/test/quick/static_clsmethod.php
```

They should not differ on any tests.

**Comment by gut** [comment]
related issue: #116

**Comment by racardoso** [comment]
-- Debug Mode
./run --threads 8 'quick/SetOpM.php' 'quick/constructor_throw.php' 'quick/debugger/break1.php' 'quick/debugger/flow.php' 'quick/debugger/flow2.php' 
'quick/debugger/flow_break_interference.php' 'quick/debugger/flow_excep.php' 'quick/debugger/flow_gen.php' 'quick/debugger/flow_gen_async.php' 
'quick/debugger/flow_gen_async_excep.php' 'quick/debugger/flow_gen_excep.php' 'quick/debugger/flow_multistep.php' 'quick/debugger/flow_small.php' 
'quick/debugger/stack1.php' 'quick/exception_destructor_1.php' 'quick/exception_destructor_4.php' 'quick/exception_many_locals.php' 
'quick/exceptions7.php' 'quick/fb_intercept.php' 'quick/float-overflow.php' 'quick/function_varargs.php' 'quick/generator_varargs.php' 
'quick/intercept.php' 'quick/intercept2.php' 'quick/profile/Setprofile.php' 'quick/profile/Setprofile_async.php' 'quick/profile/Setprofile_generic.php'
'quick/profile/setprofile-this.php' 'quick/profile/setprofile_throw.php' 'quick/retval_backtrace.php' 
'quick/sp.php' 'quick/surprise_throw.php'

-- Release Mode
./run --threads 8 'quick/constructor_throw.php' 'quick/debugger/break1.php' 'quick/debugger/flow.php' 'quick/debugger/flow2.php' 
'quick/debugger/flow_break_interference.php' 'quick/debugger/flow_excep.php' 'quick/debugger/flow_gen.php' 'quick/debugger/flow_gen_async.php' 
'quick/debugger/flow_gen_async_excep.php' 'quick/debugger/flow_gen_excep.php' 'quick/debugger/flow_multistep.php' 'quick/debugger/flow_small.php' 
'quick/debugger/stack1.php' 'quick/exception_destructor_1.php' 'quick/exception_destructor_4.php' 'quick/exception_many_locals.php' 
'quick/exceptions7.php' 'quick/fb_intercept.php' 'quick/float-overflow.php' 'quick/hh_async_closure_return_type_1.php' 
'quick/hh_async_closure_return_type_2.php' 'quick/hh_async_closure_return_type_3.php' 'quick/hh_closure_return_type_1.php' 
'quick/hh_closure_return_type_2.php' 'quick/hh_closure_return_type_3.php' 'quick/intercept.php' 'quick/intercept2.php' 
'quick/profile/Setprofile.php' 'quick/profile/Setprofile_async.php' 'quick/profile/Setprofile_generic.php' 'quick/profile/setprofile-this.php' 
'quick/profile/setprofile_throw.php' 'quick/rename_dyn_function.php' 'quick/retval_backtrace.php' 'quick/static_clsmethod.php' 
'quick/surprise_throw.php' 'quick/xenon/xenon.php' 'quick/xenon/xenon_init.php'

Fails in Debug Mode only:
'quick/SetOpM.php'
'quick/sp.php'
'quick/function_varargs.php' 
'quick/generator_varargs.php'

Fails in Release Mode only:
'quick/hh_async_closure_return_type_1.php' 
'quick/hh_async_closure_return_type_2.php' 
'quick/hh_async_closure_return_type_3.php' 
'quick/hh_closure_return_type_1.php' 
'quick/hh_closure_return_type_2.php' 
'quick/hh_closure_return_type_3.php'
'quick/xenon/xenon.php'
'quick/xenon/xenon_init.php'
'quick/rename_dyn_function.php'
'quick/static_clsmethod.php'

**Comment by igorsnunes** [comment]
Removing the optimization in Release mode, the failing tests now start to pass. See the diff below for more information:

``` diff
  diff --git a/CMake/HPHPCompiler.cmake b/CMake/HPHPCompiler.cmake
index ff658c3..b3eb2fa 100644
--- a/CMake/HPHPCompiler.cmake
+++ b/CMake/HPHPCompiler.cmake
@@ -47,10 +47,10 @@ if (${CMAKE_CXX_COMPILER_ID} STREQUAL "Clang")
   set(CMAKE_CXX_FLAGS_DEBUG          "-g")
   set(CMAKE_C_FLAGS_MINSIZEREL       "-Os -DNDEBUG")
   set(CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
-  set(CMAKE_C_FLAGS_RELEASE          "-O3 -DNDEBUG")
-  set(CMAKE_CXX_FLAGS_RELEASE        "-O3 -DNDEBUG")
-  set(CMAKE_C_FLAGS_RELWITHDEBINFO   "-O2 -g -DNDEBUG")
-  set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG")
+  set(CMAKE_C_FLAGS_RELEASE          "-g -DNDEBUG")
+  set(CMAKE_CXX_FLAGS_RELEASE        "-g -DNDEBUG")
+  set(CMAKE_C_FLAGS_RELWITHDEBINFO   "-g -DNDEBUG")
+  set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-g -DNDEBUG")
   set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} ${LLVM_OPT} -w")
   set(CMAKE_CXX_FLAGS "-Wall ${CMAKE_CXX_FLAGS} -std=gnu++11 -stdlib=${CLANG_STDLIB} -fno-omit-frame-pointer -Woverloaded-virtual -Wno-deprecated -Wno-strict-aliasing -Wno-write-strings -Wno-invalid-offsetof -fno-operator-names -Wno-error=array-bounds -Wno-error=switch -Werror=format-security -Wno-unused-result -Wno-sign-compare -Wno-attributes -Wno-maybe-uninitialized -Wno-mismatched-tags -Wno-unknown-warning-option -Wno-return-type-c-linkage -Qunused-arguments ${LLVM_OPT}")
 # using GCC
@@ -114,10 +114,10 @@ elseif (${CMAKE_CXX_COMPILER_ID} STREQUAL "GNU")
   # Generic GCC flags and Optional flags
   set(CMAKE_C_FLAGS_MINSIZEREL       "-Os -DNDEBUG")
   set(CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
-  set(CMAKE_C_FLAGS_RELEASE          "-O3 -DNDEBUG")
-  set(CMAKE_CXX_FLAGS_RELEASE        "-O3 -DNDEBUG -fno-gcse ${CMAKE_CXX_OMIT_LEAF_FRAME_POINTER} --param max-inline-insns-auto=100 --param early-inlining-insns=200 --param max-early-inliner-iterations=50 --param=inline-unit-growth=200 --param=large-unit-insns=10000")
-  set(CMAKE_C_FLAGS_RELWITHDEBINFO   "-O2 -g -DNDEBUG")
-  set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG")
+  set(CMAKE_C_FLAGS_RELEASE          "-O0 -g -DNDEBUG")
+  set(CMAKE_CXX_FLAGS_RELEASE        "-O0 -g  -DNDEBUG -fno-gcse ${CMAKE_CXX_OMIT_LEAF_FRAME_POINTER} --param max-inline-insns-auto=100 --param early-inlining-insns=200 --param max-early-inliner-iterations=50 --param=inline-unit-growth=200 --param=large-unit-insns=10000")
+  set(CMAKE_C_FLAGS_RELWITHDEBINFO   "-O0 -g -DNDEBUG")
+  set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O0 -g -DNDEBUG")
   set(CMAKE_C_FLAGS                  "${CMAKE_C_FLAGS} ${GNUCC_OPT} -w")
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=gnu++11 -ffunction-sections -fdata-sections -fno-gcse -fno-omit-frame-pointer -Woverloaded-virtual -Wno-deprecated -Wno-strict-aliasing -Wno-write-strings -Wno-invalid-offsetof -fno-operator-names -Wno-error=array-bounds -Wno-error=switch -Werror=format-security -Wno-unused-result -Wno-sign-compare -Wno-attributes -Wno-maybe-uninitialized -Wno-unused-local-typedefs -fno-canonical-system-headers -Wno-deprecated-declarations -Wno-unused-function -Wvla ${GNUCC_OPT} ${GNUCC_PLAT_OPT}")
   if(STATIC_CXX_LIB)
```

**Comment by racardoso** [comment]
Editing hphp/runtime/CMake/hphp_runtime_static.dir/build.cmake

Changes CXX_FLAGS to -O0 for mc-generator.cpp solves:

cat quick/hh_async_closure_return_type_1.php.diff
cat quick/hh_async_closure_return_type_2.php.diff
cat quick/hh_async_closure_return_type_3.php.diff
cat quick/hh_closure_return_type_1.php.diff
cat quick/hh_closure_return_type_2.php.diff
cat quick/hh_closure_return_type_3.php.diff
cat quick/rename_dyn_function.php.diff
cat quick/static_clsmethod.php.diff

```
hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/mc-generator.cpp.o: hphp/runtime/CMakeFiles/hphp_runtime_static.dir/flags.make
hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/mc-generator.cpp.o: hphp/runtime/vm/jit/mc-generator.cpp
    $(CMAKE_COMMAND) -E cmake_progress_report /home/rcardoso/hhvm-next/hhvm/CMakeFiles $(CMAKE_PROGRESS_392)
    @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/mc-generator.cpp.o"
    cd /home/rcardoso/hhvm-next/hhvm/hphp/runtime && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/hphp_runtime_static.dir/vm/jit/mc-generator.cpp.o -c /home/rcardoso/hhvm-next/hhvm/hphp/runtime/vm/jit/mc-generator.cpp

hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/mc-generator.cpp.i: cmake_force
    @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/hphp_runtime_static.dir/vm/jit/mc-generator.cpp.i"
    cd /home/rcardoso/hhvm-next/hhvm/hphp/runtime && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/rcardoso/hhvm-next/hhvm/hphp/runtime/vm/jit/mc-generator.cpp > CMakeFiles/hphp_runtime_static.dir/vm/jit/mc-generator.cpp.i

hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/mc-generator.cpp.s: cmake_force
    @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/hphp_runtime_static.dir/vm/jit/mc-generator.cpp.s"
    cd /home/rcardoso/hhvm-next/hhvm/hphp/runtime && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/rcardoso/hhvm-next/hhvm/hphp/runtime/vm/jit/mc-generator.cpp -o CMakeFiles/hphp_runtime_static.dir/vm/jit/mc-generator.cpp.s
```

**Comment by gut** [comment]
5 tests missing to match Debug:

```
hphp/test/quick/GLOBALS.php
hphp/test/quick/constants-SID.php
hphp/test/quick/debugger/flow.php
hphp/test/quick/debugger/flow_small.php
hphp/test/quick/debugger/stack1.php
```

**Comment by racardoso** [comment]
@gut  i'm currently working on hphp/test/quick/GLOBALS.php

**Comment by racardoso** [comment]
GLOBALS.php and  constants-SID.php works if disable optimizations for the file:

`hphp/runtime/vm/name-value-table.cpp`

**Comment by racardoso** [comment]
The piece of code on hphp/runtime/vm/name-value-table.cpp solves tests: GLOBALS.php and constants-SID.php

```
#pragma GCC optimize("O0")
#pragma GCC push_options
TypedValue* NameValueTable::lookup(const StringData* name) {
  Elm* elm = findElm(name);
  if (!elm) return nullptr;
  TypedValue* tv = derefNamedLocal(&elm->m_tv);
  return tv->m_type == KindOfUninit ? nullptr : tv;
}
#pragma GCC pop_options
```

**Comment by gut** [comment]
interesting... did you do a deeper analisys to see what else can you do besides turning off optimization? As discussed, it's not the best approach

**Comment by racardoso** [comment]
@gut not yet i'm just start to analyzing this. Yes. It's not the best approach i just paste it here to keep things updated.

**Comment by racardoso** [comment]
100% of (quick) tests passing on Release and Debug ef77bb046bb3a65bb282ecc7ac4a10f37acd8dcc. Closing this.
