### ISSUE TITLE
Create a simple decoder to test instructions

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#12]
Need to create a simple decoder to test and validate ppc64 generated instructions.
- [x] Create instructions tables to decode a ppc64 instruction.
- [x] Create masks and others structures needed by decoder.
- [x] Create a toString function to convert instruction to string.

**Comment by racardoso** [comment]
Draft are already implemented. Need to implement decoder tables for extended opcode instructions.

**Comment by racardoso** [comment]
The instruction table, mask and other structures has already been implemented. Need to update  operand masks.

**Comment by gut** [comment]
can this be closed?

**Comment by racardoso** [comment]
I have to make some adjusts yet but i will open another task for it. Closing.
