### ISSUE TITLE
Stack assertion error after return sp offset

### ISSUE THREAD

**Issue by lbianc** [PPC64/hhvm#125]
After fixed the issue https://github.com/PPC64/hhvm/issues/121, only 3 tests were fixed, all others are failing on a stack assert, when discarding parameters.

Tests failing:
cat quick/debugger/flow.php.diff
cat quick/debugger/flow_break_interference.php.diff
cat quick/debugger/flow_excep.php.diff
cat quick/debugger/flow_gen_async.php.diff
cat quick/debugger/flow_gen_async_excep.php.diff
cat quick/debugger/flow_gen_excep.php.diff
cat quick/debugger/flow_multistep.php.diff
cat quick/debugger/flow_small.php.diff
cat quick/debugger/stack1.php.diff

**Comment by gut** [comment]
I guess you can close this one after 0145f1a109671bd38df97a5c38ebd1a49b5d5b11 and 210deaf6e092fef120456f8a88ecca550ba8e790 , right?

**Comment by lbianc** [comment]
Yes, closing. Tks!
