### ISSUE TITLE
OCAML compilation error [Hack]

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#128]
When try compile hhvm/hack with ocaml 4.04 we got the following error:

```
File "utils/sys_utils.ml", line 318, characters 39-51:
Error: This expression has type ?to_dir:bool -> string -> string -> unit
but an expression was expected of type string -> string -> unit
```

This not happens using 4.03 version:
For a temporary fix just checkout ocaml to b626516a327688487054913d9d61cef3473c29b9.

**Comment by gut** [comment]
Currently (6b471d6d5bdabfa9dd2da10d99f9b9159524df0f) even with the specific oCaml version that racardoso mentioned, I have the following issue when compiling hack:
`Fatal error: exception Invalid_argument("output_value: abstract value (outside heap)")`

taking a closer look. I'm also keeping in mind this comment https://reviews.facebook.net/D56079#1080951 and seeing if it can be fixed neatly somehow.

**Comment by racardoso** [comment]
I have some compilation error with hack after the last merge with upstream. I solve this made a `make clean` at hack folder and `rm -rf src/_build`

**Comment by gut** [comment]
@racardoso: specially when something new is updated in hack directory but our MakeFiles are not aware.

I also figured it out what was the problem on my pc: avoid building ocaml in parallel. It may break and simply building it with 1 instance solves the problem (I added the hint on [our wiki](https://github.com/PPC64/hhvm/wiki#install-ocaml))
