### ISSUE TITLE
Run oss-performance suite.

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#130]
In order to measure hhvm performance we must run oss-performance. We already run others micro benchmark but those benchmarks doesn't correspond to real workloads. Currently we just run: wordpress and "toy benchmarks" from oss-performance suite.

**Comment by racardoso** [comment]
--mediawiki gives the following error:

```
f_is_readable/1039: No such file or directory
f_is_readable/1039: No such file or directory

Warning: filemtime(): No such file or directory in /tmp/hhvm-nginxDdgEXq/mediawiki-1.26.2/includes/cache/CacheDependency.php on line 187

Warning: Failed to open http://rcardoso:8090/ () in /home/rcardoso/oss-performance/base/PerfTarget.php on line 30

Fatal error: Uncaught exception 'HH\InvariantException' with message 'Failed to find string "Obama" in http://rcardoso:8090/' in /home/rcardoso/oss-performance/base/PerfTarget.php:34
Stack trace:
#0 /home/rcardoso/oss-performance/base/PerfTarget.php(34): HH\invariant_violation()
#1 /home/rcardoso/oss-performance/base/PerfRunner.php(99): PerfTarget->sanityCheck()
#2 /home/rcardoso/oss-performance/base/PerfRunner.php(42): PerfRunner::RunWithOptionsAndEngine()
#3 /home/rcardoso/oss-performance/base/PerfRunner.php(17): PerfRunner::RunWithOptions()
#4 /home/rcardoso/oss-performance/perf.php(15): PerfRunner::RunWithArgv()
#5 /home/rcardoso/oss-performance/perf.php(19): perf_main()
#6 {main}
```

**Comment by racardoso** [comment]
--magento1 gives the following error:

```
f_is_readable/1039: No such file or directory
f_is_readable/1039: No such file or directory
f_is_file/1132: No such file or directory
f_is_writable/1001: No such file or directory
f_is_dir/1148: No such file or directory
f_is_file/1132: No such file or directory
f_is_file/1132: No such file or directory
f_is_file/1132: No such file or directory

Warning: chmod(): No such file or directory in /tmp/hhvm-nginxBVckJy/magento/app/code/core/Mage/Install/Model/Installer/Console.php on line 437

Warning: chmod(): No such file or directory in /tmp/hhvm-nginxBVckJy/magento/app/code/core/Mage/Install/Model/Installer/Console.php on line 438

```

**Comment by racardoso** [comment]
--sugarcrm 

```
f_is_dir/1148: No such file or directory

Warning: mysql_connect(): Access denied for user 'sugarcrm'@'localhost' (using password: YES) in /home/rcardoso/oss-performance/base/DatabaseInstaller.php on line 50
Fatal error: Uncaught exception 'HH\InvariantException' with message 'Failed to find string "User Name:" in http://rcardoso:8090/' in /home/rcardoso/oss-performance/base/PerfTarget.php:34
```

**Comment by racardoso** [comment]
Drupal7/8 fails with Segmentation Fault:

```
Cannot access memory at address 0x3fffa9ec1268
Cannot access memory at address 0x3fffa9ec1260
```

Maybe it's fails on fixup.

**Comment by racardoso** [comment]
Mediawiki and others frameworks fail due `connection refused` error. Those frameworks fails on x86-64 using HHVM 3.13 release or master. Reverting HHVM to 3.8 version works fine (still not test for versions > 3.8). A issue have been opened: https://github.com/facebook/hhvm/issues/6973

**Comment by leitao** [comment]
I am wondering if this bug should be against HHVM or OSS-performance project on github. From what it looks like, I think that OSS-performance might not have followed any change on HHVM project.

**Comment by racardoso** [comment]
@leitao I'm working on it but, oss-performance is just a wrap to untar the framework, lift a nginx server, runs hhvm on server mode and, call siege to made requests. The oss-performance, as far i can see, doesn't call any 'weird' features of HHVM or make any extra configuration.

**Comment by racardoso** [comment]
Last version working is 3.11. Versions 3.12 and 3.13 have the same problem (connection refused).

**Comment by racardoso** [comment]
https://github.com/hhvm/oss-performance/pull/73/commits/2749bd2fbc01f2bd1bfc1b0c469d7997397ca6e2 solves for `--mediawiki` and `--codeigniter-hello-world`. Drupal7 fails due a segmentation fault. Drupa8 fails due a database error:

```
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /tmp/hhvm-nginxZClrOd/drupal-8.0.0-beta11/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 78
Drush command terminated abnormally due to an unrecoverable error.                                                                                 [error]
Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in
/tmp/hhvm-nginxZClrOd/drupal-8.0.0-beta11/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php, line 78
```

Others frameworks:

```
  --laravel4-hello-world
  --laravel5-hello-world
  --sugarcrm-login-page
  --sugarcrm-home-page
```

Still fails due a connection refused.

**Comment by racardoso** [comment]
HHVM port for ppc64el now can run: wordpress, drupal7, mediwiki, magento1, toy-\* and, codeigniter-hello.  Others frameworks don't run even on x86-64 and almost all performance numbers published about HHVM focuses on wordpress, drupal7 and, mediwiki frameworks. So i guess we can close this task now.
