### ISSUE TITLE
Implement atomic instruction decqmlock

### ISSUE THREAD

**Issue by lbianc** [PPC64/hhvm#132]
The VASM decqmlock need to be executed as an atomic instruction and for that, the following development must be made:
- [x] Create the asm of PPC64 for ldarx and stdcx.  
- [x] Create the VASM ldarx and stdcx.
- [x] Create the decqmlock, which will use the above instructions as mentioned in the POWER ISA documentation, on page 830.

**Comment by lbianc** [comment]
The need of this instruction comes up after the merge with the master branch.

**Comment by racardoso** [comment]
Already implemented but we have regressions: 5 tests Debug/Release

```
5 tests failed
(╯°□°）╯︵ ┻━┻

See the diffs:
cat quick/array_access.php.diff
cat quick/magic-get-dtors.php.diff
cat quick/setg-dtor.php.diff
cat quick/sets-dtor.php.diff
cat quick/vector-unwind-decref.php.diff
```

**Comment by racardoso** [comment]
This issue has been solved. The failed tests are not related and has been fixed. So this is "stalled". Closing now.
