### ISSUE TITLE
Add support for hints on branch predictions

### ISSUE THREAD

**Issue by igorsnunes** [PPC64/hhvm#133]
Some branches can be used with hints, in order to enhance performance. A good example is the following code extracted from ucomisd:

``` cpp
void Vgen::emit(const ucomisd& i) {
  ppc64_asm::Label notNAN;
  emit(fcmpu{i.s0, i.s1, i.sf});
  a.bc(notNAN, BranchConditions::CR0_NoOverflow);
  {
    // Set "negative" bit if "Overflow" bit is set. Also, keep overflow bit set
    a.li64(rAsm, 0x99000000, false);
    a.mtcrf(0xC0, rAsm);
    copyCR0toCR1(a, rAsm);
  }
  notNAN.asm_label(a);
}
```

The overflow is unlilkely to happen. So the branch (bc) could use a hint in order to make a better use of the pipeline.

**Comment by igorsnunes** [comment]
On ef0005c07430420409cedb0f3fd82bc4e10f6cef a complete support for branch prediction on jcc was implemented.

A new vasm was implemented, "jccprob", and was used on code-gen-cf.h. If a code block is marked as "cold", a jccprob is emmited in order to execute an unlikely jump to that block.

This approach has not produced good results until now. A performance analysis (using perf) was made using bubblesort with a large and completely unordered input array, and also executing pidgits using 100000 as input. The comparison was made between binaries generated by ef0005c07430420409cedb0f3fd82bc4e10f6cef  and f6911147d6d579801b5139720a029c7a44a4564f .

The results showed that branch misses were not a problem: they corresponded to 2,7% in the worst case between all tests runned. Also, the results generated by ef0005c07430420409cedb0f3fd82bc4e10f6cef were slower than f6911147d6d579801b5139720a029c7a44a4564f .

**Comment by gut** [comment]
I guess we can close this task and the branch, right? It's documented on this issue how to implement it, in case we choose to do it in the future.

**Comment by igorsnunes** [comment]
Closed.
