### ISSUE TITLE
Use TOC pointer for referencing C++ addresses on JIT code

### ISSUE THREAD

**Issue by lbianc** [PPC64/hhvm#134]
Instead of loading the function address with `li64`, use a load with TOC pointer to reduce code size (from 5 to 1 instructions).

**Comment by igorsnunes** [comment]
As it can be seen on eb9b1499ab87bdb9ce19fc0cb00efd6fec73135e , on oss performance TOC gets full easily. So in order to reduce the amount of nops using this approach, it may be necessary to grow TOC dinamcally.

**Comment by brunoalr** [comment]
Although aimed at AIX, this link provide some insight on strategies to overcome TOC overflow.

http://www.ibm.com/developerworks/rational/library/overview-toc-aix/#authorN10045

**Comment by gut** [comment]
Are you using this?
https://github.com/PPC64/hhvm/blob/next/hphp/runtime/vm/jit/code-cache.h#L37-L39

**Comment by lbianc** [comment]
Thais is very similar to the TOC, maybe much easier and ready to use.

**Comment by gut** [comment]
I was actually more worried about it having a better cache performance for some reason. It might be interesting to try it.
