### ISSUE TITLE
Port disasm class

### ISSUE THREAD

**Issue by igorsnunes** [PPC64/hhvm#136]
In order to make TC_DUMP to work it is necessary to port disasm class (disasm.h and disasm.cpp). These two files have some "ifdefs" to include or not libxed functions. In order to complete the port it will be necessary to substitute the code inside those delimiters with equivalent functions for powerpc64.

**Comment by gut** [comment]
@igorsnunes as you pointed out, this can be closed now, right?

**Comment by igorsnunes** [comment]
@gut, @lbianc  was working on this issue. I think he is the one who must decide if this issue must be closed or not.

**Comment by lbianc** [comment]
Currently it is working, but there is one part missing, the one that adds the description of the branch address on these instructions.
We can close this and open a new enhancement for that, what do you think?

**Comment by gut** [comment]
Good idea. Can you please do it?

**Comment by gut** [comment]
well, it looks like you didn't :-), 

as it's a development tool and we're actually satisfied with the current output. I'll close this task and will not open another was as enhancement. Ok?
