### ISSUE TITLE
Fix merge upstream problems.

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#137]
Today i was trying to merge master on branch next after merge with upstream and found some conflicts and problems:

1- Someone introduces a error define on hh_shared (Hack). Turns out our syscall must be 360, 319 is syscall number for memfd_create on x86. It's 385 for ARM.
https://github.com/facebook/hhvm/commit/c168d42be61f7f13c15a3a6dcf572c7635869af5#commitcomment-17638245
2-ARM team creates a intrinsics vasm `fabs` but we already have a intrinsic vasm `fabs`. Because they edit different lines this cant merge conflict but gives a redefined struct error on compilation. They fabs parameters are diferent so we need to check what to do in this case (rename, use they vasm, use our vasm...) https://github.com/PPC64/hhvm/blob/next/hphp/runtime/vm/jit/vasm-instr.cpp#L192

I'm on track of this because my decoder PR was rejected again due a merge conflict so i need to solve this asap.

**Comment by gut** [comment]
for the number 2- that should be no problem for us. They have the same struct so we can reuse it.

i'll give you a hand and solve this on your branch for the decoder PR, ok?

**Comment by racardoso** [comment]
I'm  working merge upstream with next...after that i will merge no-commit for-facebook branch and just pick the files i need to update like i do before. @gut i think the `fabs` macro on vasm-intr.h is different, but i'm don't look so much to it. If it's the same there should be not problem at all. Thanks for the help.

**Comment by gut** [comment]
Are you working today? I plan doing it soon so if you'll do it today, please also join on irc so we can discuss it. Otherwise I could take this chance to make some progress today.

**Comment by racardoso** [comment]
I was not planning to work today. But i will work after 13:00. 13:30 i will join to IRC
