### ISSUE TITLE
Analise usefulness of SIMD registers for PPC64

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#138]
SIMD is disabled for PPC64 at the moment. Please check if HHVM's usage would bring performance gains for PPC64.

A draft of this change in order to test is located on https://github.com/PPC64/hhvm/commits/simd-vasms-enable (82d7d231f5feca5a838c49dc98afac083e593d83). You can use it if you want.

**Comment by racardoso** [comment]
The implementation is done. But i see no performance gain: i test with microbenchmarks from PHP7 Zend and with oss-performance (wordpress, mediwiki and, drupal) and see no performance increase or decrease.

**Comment by gut** [comment]
I'd add the new stuff on next but consider leaving the SIMD switch disabled then.

**Comment by racardoso** [comment]
I still not merge this on next. Can i merge simd branch on next an close this?

**Comment by gut** [comment]
I guess. But leave SIMD usage disabled then.

**Comment by racardoso** [comment]
Close via 38eaf0b509c7f3b5920765607ce440a8eea06bcf  d7e1f035e9625481283e3970d90f5246dc43c391 b312e7fe15f84eca30ad96df6ef35c17b7311a48 572e128f3541a83f767e8fecec19b4773dcb0946  e09f20d6f0265327a43b64426e08e85e5c286964 

We don't have any performance improvement or issue enabling SIMD (tested with oss-performance and PHP7 micro benchmarks). We can enable this latter check e09f20d6f0265327a43b64426e08e85e5c286964
