### ISSUE TITLE
Use lea vasm instead of addqi vasm when no SF register is needed

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#139]
I guess a bunch of SF registers are being created and more than 1 instructions are being used when a simple add/sub is needed on our vasm emissions or lowerings.

Review our vasm-ppc64.cpp file and improve them.

**Comment by igorsnunes** [comment]
I did not find where this is happening. Could you please point it?

**Comment by gut** [comment]
you are right. We don't have it anymore. I had it in mind when I saw this:
https://github.com/PPC64/hhvm/blob/master/hphp/runtime/vm/jit/vasm-ppc64.cpp#L999
