### ISSUE TITLE
Port emitFuncBodyHelperThunk

### ISSUE THREAD

**Issue by fabioperez** [PPC64/hhvm#14]
File: `hphp/runtime/vm/jit/unique-stubs-ppc64.cpp`
- [x] Implement `load` (file: `hphp/runtime/vm/jit/vasm-ppc64.cpp`) - 710a93299e5c13dac7077b1569409f97761e1896
- [x] Implement `callm` (file: `hphp/runtime/vm/jit/vasm-ppc64.cpp`) - 
  a800716f004787a150e461e1649add6aef733a10
- [x] Port `emitCall` (file: `hphp/runtime/vm/jit/code-gen-helpers-ppc64.cpp`) - 
  fd3c569ef2e6b24af8544a205a0fa67afd824649

**Comment by gut** [comment]
Done. Check first comment for tracking purposes
