### ISSUE TITLE
Change decoder to remove NO_OPT

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#141]
Optimizations are disabled to Decoder construtor via `__attribute__((optimize(O0)))` because in release mode -O3 causes compilation to hang due his huge initialization list.  This is a static singleton constructor, it's only called once and, when trace is enabled so optimization here is not a big issue but this is very ugly. We should try refactor the Decoder so we can get rid of this `NO_OPT` thing.

**Comment by gut** [comment]
is this still valid?

**Comment by racardoso** [comment]
yes. The task here is to refactor decoder to remove the NO_OPT attribute.

**Comment by lbianc** [comment]
The `NO_OPT`' does not impact in the performance, and seems to be an issue with the arg list `_VA_ARGS__`. As there is no performance impact, it will be analyzed later.

**Comment by racardoso** [comment]
Looks like this is a GCC compiler problem. The gcc parameter `--param early-inlining-insns=200` freezes the compilation. Removing this parameter HHVM compiles. This problem not happens on x86_64 only in POWER. Was tested on gcc 4.8, 4.9 and 5.4. A bug on bugzilla was opened for this issue.

**Comment by racardoso** [comment]
closed via 3dfa3f17376fd08ee50333ade1154c416e5baeab

**Comment by gut** [comment]
@racardoso : unfortunately it doesn't look like it worked so nice... Take a look at our jenkins. Since build 115 it's taking 30-60minutes to build. I checked locally and to compile the `decoder-ppc64.cpp` with **O3** it's taking significantly longer than **O0**.

Oh wait: it took 6 minutes (O3) instead of 40s (O0). It may be something else (or linking such object)

**Comment by brunoalr** [comment]
@racardoso, @gut the compiler gives us the following note (not a warning, though):
`hphp/ppc64-asm/decoder-ppc64.cpp:156:1: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without`
