### ISSUE TITLE
Refactor SF optimization for PPC64

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#149]
Based on Daniel's pull request: https://github.com/PPC64/hhvm/pull/143

Refactor it to use a new optimization phase, similar to what is done on this simplify step: https://github.com/facebook/hhvm/commit/fa442471676c9550691c28fe31c9fee2edda0a05

Please avoid changes on `hphp/runtime/vm/jit/vasm-instr.h`. That's probably unwelcome by HHVM community.

After that, create a PR please

**Comment by daxtens** [comment]
I don't have time to do this myself, but if there's any help I can offer
please let me know.

**Comment by brunoalr** [comment]
@daxtens thanks for offering help! I'll ping you when needed.

**Comment by lbianc** [comment]
PR sent: https://github.com/facebook/hhvm/pull/7326.
