### ISSUE TITLE
Prioritize calee saved registers when allocating registers on JIT

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#153]
Currently hhvm starts allocating registers from lower index to higher, that means `r3`, `r4`... (as they are the first non-reserved registers). However, when calling a C++ function, it needs to spill those registers if the C++ function needs them as arguments.

One way to avoid that is to use calee saved registers instead, which are the non-volatile `r14` up to `r30` (actually up to `r25` as above that is also reserved).

**Comment by racardoso** [comment]
@gut can you give more details about this task? maybe a example?

**Comment by gut** [comment]
@racardoso : Hi. I tried to get an example and I just noticed this doesn't happen. It was only my impression. Sorry.
