### ISSUE TITLE
6 test fails on quick suite after last merge

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#159]
### HHVM Version
HHVM upstream/master
HHVM next branch

After the last merge we got 6 tests failing on quick suite and 73 on all suite. The tests bellow fails on quick suite in Release mode.
```
6 tests failed
(╯°□°）╯︵ ┻━┻

See the diffs:
cat quick/debugger/async_stack.php.diff
cat quick/debugger/async_stack_traversal.php.diff
cat quick/profile/Setprofile_async.php.diff
cat quick/xenon/xenon.php.diff
cat quick/xenon/xenon_crash.php.diff
cat quick/xenon/xenon_init.php.diff
```

I still need to confirm if those tests are failing only on PPC64. I created a branch next-fail with this merge: https://github.com/PPC64/hhvm/tree/next-fail

**Comment by racardoso** [comment]
Revert TOC/Relocation https://github.com/facebook/hhvm/commit/005ff3a all tests pass.

**Comment by racardoso** [comment]
In fact they merge pull request https://github.com/facebook/hhvm/pull/7389 without some commits:

> Closed with unmerged commits

Branch for-facebook-relocation_ppc64 runs fine.

**Comment by racardoso** [comment]
Also if revert PPC64 backchain refactor https://github.com/facebook/hhvm/commit/0ab232766a1d2cf5d5d11af148cd0a1505f9a6f4 all tests runs fine which suggest that something on backchain refactor is causing problem o relocation. @lbianc do you test toc/relocation with your backchain refactor?

**Comment by gut** [comment]
The backchain fix + toc/relocation raises this warning.
The backchain fix was not integrated to our next branch. I'll clean this up and backport it to next branch once I fix this

**Comment by gut** [comment]
by integrating the e4e7741 fix on master, I see the following results on test all suite:
14213 total tests
384 tests skipped
54 tests failed

accuracy: **99,6 %** ((14213 - 384 - 54) / (14213 - 384))

**Comment by racardoso** [comment]
@gut maybe i do something wrong when merge master with next branch. I tested here and works fine on master but broke lots of test on branch next. Merge left some declarations of `emitTOC()`

**Comment by racardoso** [comment]
I tested it here Debug/Release. Commit 0a59507193ccae572d699686b5f8b1a5c34a9c0e fix the problem now we have to wait for FB accept pull request. I will leave this opened since this affects upstream/master until we merge the fix on master.

**Comment by gut** [comment]
great!

**Comment by gut** [comment]
This is now solved on branch next, right?

**Comment by racardoso** [comment]
@gut yes. Closed via https://github.com/facebook/hhvm/commit/6f19dedd14ed49a1f62251298d34a009b94f4ed3 thanks
