### ISSUE TITLE
Check and document all missing points for ppc64 to have JIT working

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#17]
Besides the well known:
- [x] implement all vasm instructions on `hphp/runtime/vm/jit/vasm-ppc64.cpp` - (described by other issues)

There are also other barriers like https://github.com/PPC64/hhvm/issues/14 and to have a better planning of missing tasks, one have to take a closer look on `x64` and write it down so the tasks can be paralleled.

Please add below the tasks found with their task links referenced:

**Comment by gut** [comment]
I made a trace of all `HPHP::jit::x64` functions that are called when running a small fibonacci example then I took a closer look on those functions and added some comments as you can see below:
- `back-end-ppc64.cpp`: https://github.com/PPC64/hhvm/issues/55
  - `genCodeImpl`
  - `genBlock`
  - `do_prepareForSmash`
  - `emitSmashableJump`
  - `jmpTarget`
  - `jccTarget`
  - `jccCondCode`
- `service-requests-ppc64.cpp`: https://github.com/PPC64/hhvm/issues/56
  - `emitServiceReqWork` - already on issue #26.
  - `emitBindJ`
  - `emitBindJmpccFirst` - uses not-yet-ported ConditionCode.
- `relocation-ppc64.cpp`: currently it's a copy of x64. https://github.com/PPC64/hhvm/issues/57
  - `adjustForRelocation`
  - `adjustMetaDataForRelocation`
  - `adjustCodeForRelocation`
- `code-gen-ppc64.cpp`: mainly generic code. https://github.com/PPC64/hhvm/issues/58
  - `CodeGenerator::cgInst`
  - `CodeGenerator::cgDefSP`
  - `CodeGenerator::srcLoc`
  - `CodeGenerator::cgStLocPseudoMain`
  - `CodeGenerator::cgLdLocPseudoMain`
  - `CodeGenerator::emitTypeTest` - uses not-yet-ported ConditionCode.
  - `CodeGenerator::emitLoad` - uses SIMD (vector), maybe it's optional.
  - `emitStoreTV` - uses SIMD (vector), maybe it's optional.
  - `CodeGenerator::emitCmpInt` - uses not-yet-ported ConditionCode. It's a wrapper for cgEqInt cgNeqInt cgLtInt cgGtInt cgLteInt cgGteInt.
  - `CodeGenerator::cgJmpZero` - uses not-yet-ported ConditionCode.
  - `CodeGenerator::cgJmpNZero` - uses not-yet-ported ConditionCode.
  - `CodeGenerator::cgReqBindJmp`
  - `CodeGenerator::cgReqRetranslate`
  - `CodeGenerator::cgStStk` - depends on emitStoreTV.
  - `CodeGenerator::cgAddIntO` - uses jcc along with the not-yet-ported ConditionCode.
  - `CodeGenerator::cgCheckSurpriseFlags` - uses not-yet-ported ConditionCode and `rds` structure, which was not yet taken care.
  - `CodeGenerator::cgInterpOneCF` - needs unique-stubs function emitResumeInterpHelpers.
  - `CodeGenerator::cgInterpOne` - calls complex CodeGenerator::cgCallHelper.
- `code-gen-helpers-ppc64.cpp`: https://github.com/PPC64/hhvm/issues/59
  - `zeroExtendIfBool` - update to ppc64.
  - `emitTestSurpriseFlags` - also uses `rds` structure, which was not yet taken care.

**remember**: the vasm instructions are not listed here (see first issue comment).

**Comment by gut** [comment]
follow up on new issues created. I'll close this.

**Comment by lbianc** [comment]
After run fibonacci, the following instructions were generated by a x86_64 machine:

lea, copy, fallthru, xorl
ldimml, jmpi, load, loadl, 
storel, store, call, jmpr, 
loadqp, subqi, xorb, movb, 
addqi, ldimmb, cmplim, jcc, 
push, movzbq, shrli, callm, 
syncpoint, pop, jmp, declm, 
ud2, ret, cmpbim, nothrow, 
storebi, storeqi, ldimmq, 
bindjcc, cmpq, bindjcc1st, 
bindjmp, fallback, leap, 
setcc, addq, cmpqm, testb, 
unwind, cmpqim, testq, 
testqi, vret, testqim, 
landingpad

**Comment by lbianc** [comment]
Adding functions called while running JIT code:
- `translator-runtime.cpp`
  - `traceCallback`
  - `checkFrame`
- `mc-generator.cpp`
  - `handleServiceRequest`
  - `requestExit`
  - `emitServiceReq`
  - `bindJmpccFirst`
