### ISSUE TITLE
Update debug information for ppc64

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#2]
- [ ] Check `hphp/runtime/vm/debug/` files for correct code position information on ppc64 emitted code
- [x] Update `hphp/runtime/vm/jit/unwind-x64.cpp` or create a new unwind file for ppc64

**Comment by gut** [comment]
check `dwarf` branch

**Comment by racardoso** [comment]
I guess this task needs to be updated or closed since i guess all this tasks are done.

**Comment by gut** [comment]
as far as I remember, the first point is still open, but unfortunately nobody is working on it. 

If it's the case, then also the 'dwarf' branch can be closed.

**Comment by racardoso** [comment]
@gut why dwarf branch cannot be merged with next?

**Comment by gut** [comment]
it's only partly implemented.

**Comment by racardoso** [comment]
@gut since you work with this problem before can you fill this task with more information? Why this is need for? What's the test case for this? With more information about it someone else can work on this task if that's the case.

**Comment by gut** [comment]
I worked with this 1 year ago. I can't really say I remember a lot.

First thing we have to check is if we'll have any gain in implementing this.

**Comment by gut** [comment]
Well, this task does not seem relevant anymore. We were debugging this code since then and found no reason to implement this... I'll close this and remove the branch.

Just to keep track, the branch had this top:  https://github.com/PPC64/hhvm/tree/6ff4f7bf6193559b452b44ecb17f38a6860ddcb1
