### ISSUE TITLE
Vasm instruction incwm

### ISSUE THREAD

**Issue by lbianc** [PPC64/hhvm#28]
Vasm instruction `incwm` need to be implemented to `PPC64`.

**Comment by racardoso** [comment]
Instruction has been implemented but still need to validate implementation.

**Comment by gut** [comment]
The 425c5493a0ca1159863ed6d42d8a051ae190282b solution is faulty.
Please check this comment from `vasm-reg.h`, line 215:

```
/*
 * Result of virtual register addressing: base + (index * scale) + disp.
 *    - base is optional, implying baseless address
 *    - index is optional
 */
```

I implemented a helper function for handling this. it's called `VptrToReg` (commit 52046f201236daee6be7df289ed256a7cad4452a). You can change it to return only the address of `Vptr` (don't forget to adapt the other calls to `VptrToReg` to load it after). Then you can do your load, increment, store, which is what incwm does, right?

**Comment by racardoso** [comment]
Fixed. See commit 8241e55882de8ab15d727b0c5d6324ee27de0c00
