### ISSUE TITLE
Vasm instruction lea

### ISSUE THREAD

**Issue by lbianc** [PPC64/hhvm#29]
Vasm instruction `lea` need to be implemented to `PPC64`.

**Comment by racardoso** [comment]
The instruction lea is already implemented:
void emit(const lea& i) { a->addi(i.d, i.s.base, i.s.disp); }

That's what ARM do to implement lea:
void emit(lea& i) { a->Add(X(i.d), X(i.s.base), i.s.disp); }

Closing issue.
