### ISSUE TITLE
Port relocation-ppc64.cpp and relocation.cpp

### ISSUE THREAD

**Issue by lbianc** [PPC64/hhvm#53]
Both files are using x86 specific code, which fails when running on PPC64 machines. These files need to be deeper analyzed to be ported.

**Comment by gut** [comment]
the relevant functions for fibonacci example were exposed on https://github.com/PPC64/hhvm/issues/57.

**Comment by racardoso** [comment]
Extracted from task #57 
When analysing a fibonacci example, the following functions were required on the `x64` namespace:
- [x] `adjustForRelocation`
- [x] `adjustMetaDataForRelocation`
- [x] `adjustCodeForRelocation`

please update for `ppc64` namespace.

**Comment by racardoso** [comment]
Will be started when ppc64 port is done.

**Comment by gut** [comment]
related to #89. I'll start doing this

**Comment by gut** [comment]
until I finish this task, I'll be keeping a dirty tree on https://github.com/PPC64/hhvm/commits/relocation-work just in case somebody want to peek. When I finish, I'll squash commits and integrate it to the next.

**Comment by gut** [comment]
The feature is implemented on this changeset:
https://github.com/PPC64/hhvm/commit/b5ca3594bea8270edcfadfe53c7f64a2286eb048

Additional improvements can be done and will be analysed next. This task will be closed next when it's integrated on next branch.
