### ISSUE TITLE
Implement vasm instructions for frequently used HHIR.

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#60]
The following VASM instructions must be implemented: 
- [x] `bindjmp` - Leonardo - Removed by 86b27dd81c2ff15e9e9e7e7bd7e1ada9debb5702
- [x] `syncvmsp` - Igor
- [x] `vinvoke` - Gustavo
- [x] `vcall` - Gustavo - 41d61d351c86d18c5a6dc245c8cba7b5f4c073b7
- [x] `cmpbim` - Leonardo 81e3dd1c2234f6042cb590b6869013aff59be5e2
- [x] `cmpq` https://github.com/PPC64/hhvm/issues/51 - Fabio
- [x] `cmpqm` - Leonardo 81e3dd1c2234f6042cb590b6869013aff59be5e2
- [x] `copy2` - Fabio
- [x] `jcc` - Gustavo - e18d05dc28d7dc398b505c075b7dd5a55dd54aea
- [x] `jmp` - Gustavo
- [x] `jmpi` - Gustavo
- [x] `landingpad` - Fabio
- [x] `setcc` - Gustavo
- [x] `vretm` - Renamed to `vret` by 4a97869d8b69020e3d603300b78a79a9cab3eefb
- [x] `callfaststub` - Leonardo - Low priority not used by code-gen

Vasm instructions generated when running fibonacci in x64:
- [x] `leap` - Leonardo
- [x] `vret` - Igor
- [x] `ldimmq` - Leonardo - 81e3dd1c2234f6042cb590b6869013aff59be5e2 - missing SIMD part
- [x] `loadqp` - Rogerio - no longer relevant see e1fc6e640a59daa01c33d66077715572d4808b17
- [x] `storebi` - Rogerio
- [x] `storeqi` - Rogerio
- [X] `jmpr` - Gustavo
- [x] `bindjcc1st` - Removed by 86b27dd81c2ff15e9e9e7e7bd7e1ada9debb5702
- [x] `bindjcc` - Removed by 86b27dd81c2ff15e9e9e7e7bd7e1ada9debb5702
- [x] `cmplim` - Leonardo 81e3dd1c2234f6042cb590b6869013aff59be5e2
- [x] `cmpqim` - Gustavo
- [x] `copy` - Fabio - Missing SIMD
- [x] `declm` - Leonardo 81e3dd1c2234f6042cb590b6869013aff59be5e2
- [x] `ldimmb` - Rogerio
- [x] `shrli` - Gustavo
- [x] `syncpoint` - Igor
- [x] `testb` - Gustavo
- [x] `testq` - Fabio
- [x] `testqi` - Fabio
- [x] `testqim` - Fabio
- [x] `ud2` - Gustavo - ec4619ac2fc29fe9af251815dca83ad0847ebbe0
- [x] `nothrow` - Leonardo - Low priority not used by code-gen
- [x] `pop` - Gustavo - Low priority not used by code-gen
- [x] `push` - Gustavo - Low priority not used by code-gen
- [x] `unwind` - Low priority not used by code-gen - Igor

**Comment by gut** [comment]
**Test result of setcc:**
Input:

```
emit(setcc{CC_LE, VregSF(0), Vreg8(3)});
```

Output:

```
0x18a00000:  ble     0x18a0000c
0x18a00004:  xor     r3,r3,r3
0x18a00008:  bc      20,lt,0x18a00010
0x18a0000c:  li      r3,1
```

**Comment by racardoso** [comment]
The vasm instruction `storebi` has been implemented, however i use `li32` to load immediate value to a register before do the store. In ppc we don't have instruction who write a immediate directly to memory so we have to load it to a register before. I'm use `li32` but, maybe, we need to implement a `li8` or something.

**Comment by racardoso** [comment]
The instruction loadqp are used only by cgLdBindAddress we don't need to implement this since we can perform the same thing using a load with baseless address avoiding to implement a complex logic to get the next instruction pointer to simulate a RIP register.

**Comment by gut** [comment]
tasks implemented. Closing issue
