### ISSUE TITLE
Update translator-runtime.cpp file (2 functions)

### ISSUE THREAD

**Issue by lbianc** [PPC64/hhvm#62]
When analysing a fibonacci example, the following functions were called from inside JIT code:
- [ ] `traceCallback`
- [ ] `checkFrame`

**Comment by leitao** [comment]
Are these functions arch independent? They are breaking on our run for ppc64el?

**Comment by gut** [comment]
They do look platform independent and still no conflict was found. I'll close this task for the moment as it's deprecated.
