### ISSUE TITLE
Update for-facebook branch to use new ported oCaml in order to enable HACK language.

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#67]
There is a pull request in progress on **for-facebook** branch. There the interpreter mode is working but only for PHP. Please support also HACK as oCaml is now ported to PPC64.

**Comment by lbianc** [comment]
The OCAML ported to `PPC64` is newer that the on HHVM uses, so some changes must be done to migrate to it.
Currently to build HHVM woth OCAML on `PPC64`, follow the steps:
1. Build and install OCAML compilers (see: https://www.freelists.org/post/hhvm-ppc/Building-ocaml-on-ppc64le)
2. Add `pause` instruction (`asm volatile("or 31,31,31" : : : "memory");`) for `PPC64` in the file `hphp/hack/src/heap/hh_shared.c`
   PS. This change will be sent as a PR after the first PR, that enables interpreter mode to `PPC64`, be accepted (https://github.com/facebook/hhvm/pull/5913).
3. Ignore the warnings 3, 41 and 45 in the file `hphp/hack/src/_tags`, i. e, `<**/*.ml*>: ocaml, warn_A, warn(-3-4-6-29-35-41-45-44-48), warn_error_A`
