### ISSUE TITLE
Refactor VptrAddressToReg and X-Form instructions to use base and displacement parameters

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#69]
Currently `VptrAddressToReg` will calculate the absolute address of Vptr `s` and save it on Vreg `d`, that means only the full address is available on `d`.

X-Form instructions can use 2 registers to indicate a memory address by a base and displacement values but this is not being used at the moment. This improvement would generate in the end less assembly instructions.

Note: related to issue #68

**Comment by racardoso** [comment]
Closing see 7f87e99939b16fd0df975d0273872d6823ec0c4a and e0a091bf777907cfea43206c6c8b8ae9cc6916e8
