### ISSUE TITLE
Vasm's  for load

### ISSUE THREAD

**Issue by igorsnunes** [PPC64/hhvm#70]
Load vasms to be implemented.

Intrinsics
- [x] `ldimml` - igor
- [x] `ldimmqs` - @gusbromero
- [x] `load`

Instructions
- [x] `lea`
- [x] `loadups` - @gusbromero
- [x] `loadtqb` - @gusbromero
- [x] `loadb` - @gusbromero
- [x] `loadl`
- [x] `loadqp` - no longer relevant see e1fc6e640a59daa01c33d66077715572d4808b17 and task #60
- [x] `loadsd` - already implemented
- [x] `loadzbl`
- [x] `loadzbq`
- [x] `loadzlq`

File: vasm-ppc64.cpp

Note: the vasms ldimmq, loadqp, ldimmb and leap are also "load vasms" but were implemented in  #60

**Comment by gut** [comment]
All remaining points have been closed. Closing issue.
