### ISSUE TITLE
Port remaining unique-stubs to ppc64

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#76]
The following functions are currently a wrapper for a x64 specific function on `unique-stubs-x64.cpp`. Please implement them on `unique-stubs-ppc64.cpp`:
- [x] emitCallToExit - @gut e64faf9740fc382d3786e01e0514432125926f44
- [x] emitEndCatchHelper - @racardoso
- [x] emitFreeLocalsHelpers - @gut

The following auxiliary functions can be implemented on `unique-stubs-ppc64.h`:
- [ ] _syncForLLVMCatch - Low priority, not needed for fibonacci._
- [ ] _loadSavedRIP - Low priority, not needed for fibonacci._
- [ ] _stashSavedRIP - Low priority, not needed for fibonacci._
- [ ] _unstashSavedRIP - Low priority, not needed for fibonacci._
- [ ] _alignNativeStack - Low priority, not needed for fibonacci._
- [x] _immutableBindCallStub - Low priority, not needed for fibonacci._ @lbianc e562e45521c2f8b1a1bf16a529eaf9bc105389d4
- [x] _fcallArrayHelper - Low priority, not needed for fibonacci._ @lbianc 665070db1450ee8b71a7a4afeded87117729ca4f
- [x] _decRefGeneric - Low priority, not needed for fibonacci._ @lbianc 87e2ea5dea177f915e7a15a144083c2650f59624
- [x] _retHelper - Low priority, not needed for fibonacci._ @lbianc 87e2ea5dea177f915e7a15a144083c2650f59624
- [x] _genRetHelper - Low priority, not needed for fibonacci._ @lbianc 87e2ea5dea177f915e7a15a144083c2650f59624
- [x] _asyncGenRetHelper - Low priority, not needed for fibonacci._ @lbianc 87e2ea5dea177f915e7a15a144083c2650f59624
- [x] _retInlHelper - Low priority, not needed for fibonacci._ @lbianc 87e2ea5dea177f915e7a15a144083c2650f59624

Unique Stubs for recursive fibonacci
- [x] emitFunctionEnterHelper - @igor
- [x] emitFuncBodyHelperThunk
-  [x] emitFunctionSurprisedOrStackOverflow (depend on emitFunctionEnterHelper)
-  [x] emitBindCallStub @lbianc e562e45521c2f8b1a1bf16a529eaf9bc105389d4

**Comment by igorsnunes** [comment]
recursive fibonacci code

``` php
<?php
function fibo($n) {                   
  if ($n <= 1) {                    
    return $n;                    
  }                                  
  return fibo($n-1)+fibo($n-2);      
}

$n = 90; // Input: calculate fibonacci of 90
$f = fibo ($n);
echo $f;  // output: result of fibonacci of 90

?>
```

Patch to enable unique stubs  for recursive fibonacci.

``` cpp
diff --git i/hphp/runtime/vm/jit/unique-stubs.cpp w/hphp/runtime/vm/jit/unique-stubs.cpp
index 167d9f6..11f614a 100644
--- i/hphp/runtime/vm/jit/unique-stubs.cpp
+++ w/hphp/runtime/vm/jit/unique-stubs.cpp
@@ -626,11 +626,10 @@ void UniqueStubs::emitAll() {
   ADD(fcallHelperThunk,       emitFCallHelperThunk(cold));
 #endif
   ADD(funcBodyHelperThunk,    emitFuncBodyHelperThunk(cold));
-#if 0  // TODO(Gustavo): only to run fibonacci , do we need that much?
   ADD(functionEnterHelper,    emitFunctionEnterHelper(cold, *this));
   ADD(functionSurprisedOrStackOverflow,
       emitFunctionSurprisedOrStackOverflow(cold, *this));
-
+#if 0
   ADD(retHelper,                  emitInterpRet(cold));
   ADD(genRetHelper,               emitInterpGenRet<false>(cold));
   ADD(asyncGenRetHelper,          emitInterpGenRet<true>(cold));
@@ -638,13 +637,12 @@ void UniqueStubs::emitAll() {
   ADD(debuggerRetHelper,          emitDebuggerInterpRet(cold));
   ADD(debuggerGenRetHelper,       emitDebuggerInterpGenRet<false>(cold));
   ADD(debuggerAsyncGenRetHelper,  emitDebuggerInterpGenRet<true>(cold));
-
+#endif
   ADD(bindCallStub,           emitBindCallStub<false>(cold));
   ADD(immutableBindCallStub,  emitBindCallStub<true>(cold));
+#if 0
   ADD(fcallArrayHelper,       emitFCallArrayHelper(hot()));
-
   ADD(decRefGeneric,  emitDecRefGeneric(cold));
-
 #endif
   ADD(callToExit,       emitCallToExit(main));
   ADD(endCatchHelper,   emitEndCatchHelper(frozen, *this));
```

**Comment by gut** [comment]
bump.
Let's close this issue? Is there still anything to be done?

**Comment by racardoso** [comment]
@gut I'm closing this. If something else appear we can open another task. 
`syncForLLVMCatch` - It's x64 only we just return a empty RegSet.
`loadSavedRIP`, `stashSavedRIP`, `unstashSavedRIP` and, `alignNativeStack` -  Doesn't exists anymore (i guess these functions was killed after Max Wang refactor ? )
