### ISSUE TITLE
MemoryRef assertion fail

### ISSUE THREAD

**Issue by igorsnunes** [PPC64/hhvm#81]
HHVM crashes in /hhvm/hphp/runtime/vm/jit/vasm-reg-inl.h:179 on assertion "seg == DS". This bug happens on storebi.

**Comment by leitao** [comment]
I am wondering what does it mean "seg == DS", since x86 is using a flat
memory model, as ppc64, right?

**Comment by gut** [comment]
No, **x64** is using segmented memory model by prefixing `0x64` for `FS` or `0x65` for `GS` segment. That prefixing takes place only on **load**, **storebi** and **addqim** vasm instructions.
