### ISSUE TITLE
port specific assembly hash/memset/memcpy instructions to POWER

### ISSUE THREAD

**Issue by leitao** [PPC64/hhvm#83]
There are some hash, malloc and memset instructions that are implemented for SSE (x86) and it is using fallback on power. These instructions need to be implemented on POWER using VSX.

These are the files that contains these instructions:

hphp/util/hash-crc.S
hphp/util/memcpy-x64.S
hphp/util/memset-x64-avx2.S

**Comment by leitao** [comment]
There were some effort to port these instructions to POWER already.

https://sourceware.org/ml/libc-alpha/2011-07/msg00123.html

**Comment by leitao** [comment]
Glibc also has optimizations for memset and memcopy already at sysdeps/powerpc/powerpc64/power7

**Comment by lbianc** [comment]
@gromero Have you checked the performance using the native GlibC functions (memcpy, memset, etc) for PPC64?

**Comment by gromero** [comment]
@lbianc I just checked performance of native glibc memcpy(), but against a specific code of mine. I never, for instance, checked glibc memcpy() performance in comparison with HHVM memcpy(). So I think haven't much to say about it on HHVM context.

**Comment by racardoso** [comment]
strcmp (0% performance increase) memset  (no more than 2% in some specific cases) and memcpy (0%) was implemented. No real performance increase. hash-crc was not implemented. Close this via 7c17e1b
