### ISSUE TITLE
Port smashable-instr-ppc64.cpp methods

### ISSUE THREAD

**Issue by lbianc** [PPC64/hhvm#84]
The file `smashable-instr-ppc64.cpp` contains the following methos that need to be ported to PPC64:
- [x] emitSmashableMovq - @lbianc de805fa6df2b83fb147d5a6232a5562526d934b4
- [x] emitSmashableJccAndJmp - @lbianc de805fa6df2b83fb147d5a6232a5562526d934b4
- [x] emitSmashableCmpq - @racardoso 875b241956da5e1cd000ea029eac854e08091045 @gut f510c09b3a437ae6cf6b2270e7a1d00dccd9c28d
- [x] emitSmashableCall - @racardoso b3bdb20e2d3d883b1c4c58db055ecf7c8a5bc61f @gut 5f25ae5f117bb039ab7a656436faa5279ef160f8 
- [x] emitSmashableJmp - @gut 781ae0374e9dc19b07042f6f2036960cce3112ed
- [x] emitSmashableJcc - @lbianc f9a0b9544e4cc2927e5fa0c320b15467244f2ee2
- [x] smashCall - @gut 31c03ae82174dccf8cc4f8f8852c16247ab29b41
- [x] smashCmpq - @gut f510c09b3a437ae6cf6b2270e7a1d00dccd9c28d
- [x] smashJmp - @lbianc b98532fc41eee586ded67ebcbca4e038b75c1906
- [x] smashJcc - @lbianc 5ef088bc9a77ad18dc2783c6431392838cb7763c
- [x] smashMovq - @gut a2e583ae0dc3920b169b007dc83583a1e4f9f7d2
- [x] smashableMovqImm - @gut a2e583ae0dc3920b169b007dc83583a1e4f9f7d2
- [x] smashableCmpqImm - @gut f510c09b3a437ae6cf6b2270e7a1d00dccd9c28d
- [x] smashableCallTarget - @gut ac0c7a16c6a89f749b94586d356503c61cc5d3a6 31c03ae82174dccf8cc4f8f8852c16247ab29b41
- [x] smashableJmpTarget - @gut 22486c5f937f72a59261a2c656e5024c51222fea
- [x] smashableJccTarget - @gut 22486c5f937f72a59261a2c656e5024c51222fea
- [x] smashableJccCond - @gut 4e6c2ae1a456f6465a07de37e809949c62574eda

[Reference to smashable instructions](https://github.com/PPC64/hhvm/blob/next/hphp/runtime/vm/jit/smashable-instr.h)

**Comment by gut** [comment]
As commented on 875b241956da5e1cd000ea029eac854e08091045 I'd suggest to mark the smashable instructions as `not_implemented()` and only after a deeper analysis of the caller to these functions we should implement it. What do you think?
