### ISSUE TITLE
Implement a patchImmediate to avoid checking if it's greater than 16bits

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#85]
The idea is to lower immediates just like `patchVptr` is done. Consider using template classes if you implement it for several variants like `uint32_t`, `uint64_t`, `Immed` and `Immed64` types.

Also consider the interactions of `Vptr`'s displacement field with `patchVptr` function being called (should one be called before the other?).

A related task is to update`patchVptr` to avoid calling `ldimmq` for a displacement that is too big (should not care about it if there is a `patchImmediate`).

**Comment by gut** [comment]
This task may be of @racardoso or @gusbromero interest.

**Comment by leitao** [comment]
What is the priority for this task?

**Comment by igorsnunes** [comment]
Medium->High.
It is important to clean the code and isolate functionalities before the next pull request.
