### ISSUE TITLE
Improve performance on POWER

### ISSUE THREAD

**Issue by leitao** [PPC64/hhvm#86]
Profiling show the following functions as the most offenders:
- get_cpu_frequency
- MD5Transform
- PrologueCallersRec
- hash_string_i_fallback
- AtomicHashArray
- hphp_hash_map

**Comment by gut** [comment]
What is the priority on this one?

**Comment by leitao** [comment]
I would mark this as ML3, where:

ML1 = fibonacci
ML2 = wikimedia
ML3 = high performance workloads.

**Comment by lbianc** [comment]
@leitao, can you add here the configurations and which tools you used for running it again on JIT mode?

**Comment by gromero** [comment]
@lbianc @leitao is on hols, so I dare a wild guess: apt-get install linux-tools-common; sudo perf record <hhvm_binary pointing to some test or even without any>; sudo perf annotate will provide a profile as per function.

**Comment by lbianc** [comment]
@gromero, which tests were executed for profiling?

**Comment by gromero** [comment]
@lbianc hm, that's good question. At least without any test to get a profile for get_cpu_frequency function I guess. But not sure about the other ones.

**Comment by gut** [comment]
shouldn't we work on these points now?

**Comment by racardoso** [comment]
I guess we can close this issue. Currently we are profiling HHVM again with new tools to identify possible performance issues. This profile was taken almost a year ago and many things have change since then. If we identify any of those functions on analysis again i suggest we should open separated tasks for then.

**Comment by gut** [comment]
I agree. Let's work on what's profiled. I guess Breno's analysis is based on interpreted mode (there was no ppc64 JIT at that time), so it might be somehow out of scope.
