### ISSUE TITLE
Investigate why loadb is failing when handling X-form

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#91]
The commit 0417ea3831a19768179d0a416b4b19ca908d9f40 is a counter-measure to a sleeping bug: when `loadb` has a Vptr with index, the `lbzx` instruction should be used but the code breaks afterwards, investigate what is going on and revert this commit, possibly with some other fix as well.

**Comment by racardoso** [comment]
Last updates resolve this issue. I only enable lbzx again on code.

**Comment by gut** [comment]
a4d7b64639eea0cb2fc89dac69ee6189935f1d82 works
