### ISSUE TITLE
Printing incorrect condition codes for ppc64

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#97]
print-vasm printng incorrect condition codes for ppc64. This happens because conditional code print was not yet ported. It's using x64 codes:

``` C++
void imm(ConditionCode cc) { str << sep() << cc_names[cc]; }
```

```
asm-x64.h
// names of condition codes, indexable by the ConditionCode enum value.
extern const char* cc_names[];
```

Needs to implement a cc_names to using at FormatVisitor class on vasm-print.cpp.

**Comment by gut** [comment]
`ConditionCode` is supposed to be arch-independent (even though it's perfect for x64) as you see that code-gen-x64.cpp (which is also arch-independent per design) emit conditional jumps and uses that classes.

Of course we convert `ConditionCode` to `BranchParameters` but I'm not sure if this task is indeed valid. Probably it's desired to print the input, hence a `ConditionCode`, right? If so, please close this task.

**Comment by racardoso** [comment]
This task has been opened 4 months ago. I will check this and if it's not valid anymore i'll close this issue.

**Comment by racardoso** [comment]
I will close this issue. I we need to convert ConditionCode to BranchParameters we can open another issue,

**Comment by gut** [comment]
it's already done:
https://github.com/PPC64/hhvm/blob/next/hphp/ppc64-asm/asm-ppc64.h#L210
